# .github/workflows/nojekyll.yml
name: Add .nojekyll and Deploy GitHub Pages

on:
  workflow_call:
    inputs:
      github_token:
        description: 'GitHub token'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .nojekyll file
        run: echo > .nojekyll

      - name: Commit .nojekyll file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .nojekyll
          git commit -m 'Add .nojekyll file'
          
          # Check if gh-pages branch exists
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "gh-pages branch exists"
          else
            echo "gh-pages branch does not exist"
          fi

          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ inputs.github_token }}
          publish_branch: gh-pages
          publish_dir: ./ 