name: Add .nojekyll and Deploy GitHub Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .nojekyll file
        run: echo > .nojekyll

      - name: Commit .nojekyll file
        run: |
          git config --global user.name 'Ponttablazat'
          git config --global user.email 'tvincedc@gmail.com'
          git add .nojekyll
          git commit -m 'Add .nojekyll file'
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./